version: "3"

networks:
  database:

services:
  postgres:
    image: postgres:latest
    container_name: wallet-postgres
    ports:
      - 5432:5432

    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=rootpostgres
      - POSTGRES_PASSWORD=wallet_190_pass
      - POSTGRES_DB=walletship

    volumes:
      - ./volumes/data:/var/lib/postgresql/data

    networks:
      - database
