version: "3"

networks:
  database:

services:
  mariadb:
    image: mariadb:latest
    container_name: wallet-mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wallet_190_pass
      - MYSQL_DATABASE=wallet
    volumes:
      - ./volumes/data:/var/lib/mysql
    networks:
      - database